
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      ‘Ў®аЄ  ­ з в  18.04.2025 14:43:08.
      
      Џа®ҐЄв "C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      PrepareForBuild:
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\".
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        ‘®§¤ ­ЁҐ "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ” ©« "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      ‘Ў®аЄ  Їа®ҐЄв  "C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      
      ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
          ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
          ЋиЁЎ®Є: 0
      
      Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.42
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/PROJECTS/chadity/AdvancedDockingSystem/_build/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/PROJECTS/chadity/AdvancedDockingSystem/_build/CMakeFiles/CMakeScratch/TryCompile-rx1x9p"
      binary: "C:/PROJECTS/chadity/AdvancedDockingSystem/_build/CMakeFiles/CMakeScratch/TryCompile-rx1x9p"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/PROJECTS/chadity/AdvancedDockingSystem/_build/CMakeFiles/CMakeScratch/TryCompile-rx1x9p'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_f59af.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.6.3+07e294721 for .NET Framework
        ‘Ў®аЄ  ­ з в  18.04.2025 14:43:09.
        
        Џа®ҐЄв "C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\CMakeScratch\\TryCompile-rx1x9p\\cmTC_f59af.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        PrepareForBuild:
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_f59af.dir\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\CMakeScratch\\TryCompile-rx1x9p\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_f59af.dir\\Debug\\cmTC_f59af.tlog\\".
        InitializeBuildStatus:
          ‘®§¤ ­ЁҐ "cmTC_f59af.dir\\Debug\\cmTC_f59af.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f59af.dir\\Debug\\\\" /Fd"cmTC_f59af.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.36.32532 ¤«п x64
          CMakeCXXCompilerABI.cpp
          (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f59af.dir\\Debug\\\\" /Fd"cmTC_f59af.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\CMakeScratch\\TryCompile-rx1x9p\\Debug\\cmTC_f59af.exe" /INCREMENTAL /ILK:"cmTC_f59af.dir\\Debug\\cmTC_f59af.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/PROJECTS/chadity/AdvancedDockingSystem/_build/CMakeFiles/CMakeScratch/TryCompile-rx1x9p/Debug/cmTC_f59af.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/PROJECTS/chadity/AdvancedDockingSystem/_build/CMakeFiles/CMakeScratch/TryCompile-rx1x9p/Debug/cmTC_f59af.lib" /MACHINE:X64  /machine:x64 cmTC_f59af.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_f59af.vcxproj -> C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\CMakeScratch\\TryCompile-rx1x9p\\Debug\\cmTC_f59af.exe
        FinalizeBuildStatus:
          ” ©« "cmTC_f59af.dir\\Debug\\cmTC_f59af.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
          ЋЎа йҐ­ЁҐ Є "cmTC_f59af.dir\\Debug\\cmTC_f59af.tlog\\cmTC_f59af.lastbuildstate".
        ‘Ў®аЄ  Їа®ҐЄв  "C:\\PROJECTS\\chadity\\AdvancedDockingSystem\\_build\\CMakeFiles\\CMakeScratch\\TryCompile-rx1x9p\\cmTC_f59af.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        
        ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
            ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
            ЋиЁЎ®Є: 0
        
        Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.31
        
      exitCode: 0
...
